### Obtener las reservas diarias de un profesional (HU10)
GET http://localhost:3000/api/bookings/professional/bookings?date=2025-08-02
// Authorization: Bearer <your-jwt-token>

### Booking service HU03
POST http://localhost:3000/api/bookings
Content-Type: application/json

{
  "clientId": 2,
  "serviceId": 3,
  "date": "2025-08-07T09:00:00Z",
  "startTime": "09:00",
  "endTime": "11:00",
  "status": "pending"
}


