CREATE TABLE IF NOT EXISTS custumers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    custumerClass VARCHAR(50) NOT NULL,
    items TEXT[] NOT NULL DEFAULT '{}',
    attack INTEGER NOT NULL DEFAULT 0,
    mana INTEGER NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL DEFAULT 0,
    level INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_custumers_updated_at
    BEFORE UPDATE ON custumers
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
